### ISSUE TITLE
Add endpoints for courses

### ISSUE THREAD

**Issue by dotcs** [nils-braun/learningpage#13]
Right now we only have API endpoints for the course contents (= individual notebooks). It would be nice to also have endpoints available for the `Course` model. Given that we could create an overview page in which we show all available courses. When users click on one of the courses we can show more details about the content groups (= course syllabus) similar to what Coursera does [here](https://www.coursera.org/learn/python-data#syllabus).

@nils-braun What do you think?

**Comment by nils-braun** [comment]
Sure, that is the plan. But we agreed to have the first version ready as quickly as possible without the capabilities of having more than one course ;-) That is why it is not implemented so far.
But we should keep it in our milestones.

**Comment by nils-braun** [comment]
Solved via #14
